### ISSUE TITLE
Using string instead of constant for describe argument causes data leakage

### ISSUE THREAD

**Issue by jasonswett** [metaskills/minitest-spec-rails#115]
I created a repo [here](https://github.com/jasonswett/leak_test) which reproduces the bug and gives reproduction instructions. I imagine that that's a sufficient explanation, but if not, I'm happy to explain further!

I'm happy to try to diagnose/fix as well but I wanted to get this issue opened as a first step and I haven't yet dived into the code for `minitest-spec-rails` to see what the cause might be.

**Comment by benjaminwood** [comment]
Oh Hey @jasonswett 👋🏻  - this problem still exists. I've tracked it down a bit further, it'll leak data _if it's not a class_ because of this condition here:

https://github.com/metaskills/minitest-spec-rails/blob/1d09d588c1ca02ce0563ffc7ef48a65bd05b52af/lib/minitest-spec-rails/init/active_support.rb#L11

I bumped into this because we were passing a module as the description and doing so causes data leakage (no transaction rollback).

When the block returns false, the call to spec_type [here](https://github.com/minitest/minitest/blob/master/lib/minitest/spec.rb#L88) will return `Minitest::Spec < Minitest::Test` wich is the [default](https://github.com/minitest/minitest/blob/master/lib/minitest/spec.rb#L128). However, if the block returns true then `spec_type` returns `ActiveSupport::TestCase < Minitest::Test` (and `ActiveSupport::TestCase` handles the transaction properly).

Changing the block to `register_spec_type(self) { true }` resolve it, but I'm not certain that it is correct. I'm going to go ahead and submit a PR with this change, and I'll let @metaskills decide if it's the correct solution 😄

**Comment by metaskills** [comment]
Really open to any sort of PR. Also really happy you were able to dig into the technical details.
