### ISSUE TITLE
Shouldn't depend on rails gem

### ISSUE THREAD

**Issue by quinn** [metaskills/minitest-spec-rails#80]
If you're concerned about locking out older versions of Rails, maybe instead depend on >= activesupport v4?

**Comment by metaskills** [comment]
Hey Quinn, thanks for posting. My goal is to support Rails 2.3 and upward. I've been using this gem/technique for that long :) 

Please see this section of the docs which outlines which version to pick for which Rails version you are running: https://github.com/metaskills/minitest-spec-rails#usage We have to lock Rails versions for different major/minor versions of our gem because the "technique" to allow this gem to work depends on Rails versions which in turn is mostly the case on what version ActiveSupport specs to Minitest. But either way, you should be able to use that gem no matter what Rails version you are on. Does that help address your issue?

**Comment by quinn** [comment]
@metaskills I created this as a side effect of this issue:

https://github.com/cerebris/jsonapi-resources/pull/860

Maybe then it would be best to depend on "railties"? This all started when I was trying to rid my Gemfile.lock file of sprockets. I wish gems had the concept of "peer dependencies". 

I specifically wanted to run that gem's test suite without all of rails dependencies to confirm that I had included the right things to make sure everything passed. The only way to achieve this was by vendoring minitest-spec-rails and modifying it's gemfile. That's what I did, and it worked, so for my purposes this is no longer necessary.. I can make a PR to resolve this for this gem as well if you see any value in it, otherwise you can just close this issue :) thanks !

**Comment by metaskills** [comment]
@quinn Thanks for the context. Really dig that `jsonapi-resources` gem uses this gem as a dev dependency :) 

I am not sure which way to go here. This gem wants to hook into various Railties like ActionMailer, ActionController, and ActiveJob. I do think we do this in such a way that would only load what we need if a certain component is present. That said, if you wanted to make a pull request which changed our dep to `railties` that would be cool with me.
