### ISSUE TITLE
When test methods are mixed with describe blocks, they get run multiple times sometimes.

### ISSUE THREAD

**Issue by icantrap** [metaskills/minitest-spec-rails#82]
The following test runs two assertions:

```ruby
class DudeTest < ActiveSupport::TestCase
  def test_truthiness
    puts 'dping'
    assert true
  end

  describe 'A context' do
    it 'should test truthiness' do
      puts 'cping'
      assert true
    end
  end
end
```

The reversing the order of the test method and the describe block results in three assertions, the test method having been run twice.

```ruby
require 'test_helper'

class DudeTest < ActiveSupport::TestCase
  describe 'A context' do
    it 'should test truthiness' do
      puts 'cping'
      assert true
    end
  end

  def test_truthiness
    puts 'dping'
    assert true
  end
end
```

Shouldn't they effectively run the same number of assertions? I created a minimal Rails project that demonstrates the issue [here](https://github.com/icantrap/minitest-spec-rails-sample).

**Comment by metaskills** [comment]
### Summary

You can not mix unit method names like `test_` when using the spec syntax. Especially if that method is defined after the context class, as you noticed.

### In Detail

So yes, this simple setup...

```ruby
class FooTest < ActiveSupport::TestCase
  describe 'context' do
    it 'foo' do
      assert true
    end
  end
  def test_foo
    assert true
  end
end
```

... when run does indeed run the test twice.

```shell
$ rake test TESTOPTS="-v"
FooTest#test_foo = 0.00 s = .
FooTest::context#test_0001_foo = 0.00 s = .
FooTest::context#test_foo = 0.00 s = .
```

What is happening is that when Minitest's spec syntax creates a describe it actually creates a sub class. As part of that process, it nukes all the test methods in this new child/context class. See:

* https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L71-L88
* https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L259-L270
* https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L167-L171

Since the test method is defined after the class is created, we see it run in the child/context class. This does not happen when using the `it` spec method because it removes the method from the children classes as part of the implementation. See:

* https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L220

**Comment by icantrap** [comment]
Thanks for looking into this. I didn't realize this issue was contained completely in seattlerb/minitest.

**Comment by metaskills** [comment]
Same! I had experienced this issue before and never went spelunking into the code till now. It does not feel like an issue either. Just a gotcha. To that end I am going to close this issue but if you or anyone feels like they want to add this to the [gotchas](https://github.com/metaskills/minitest-spec-rails#gotchas) section of the README with a PR, I would be in favor of it. Cheers!
